name: adb_monitor
description: "Monitor Adb devices connection"
version: 0.0.1
homepage: "https://github.com/rohitsangwan01/adb_monitor"

environment:
  sdk: ^3.5.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: 2.3.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  ffi: ^2.1.0
  ffigen: ^11.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true